name: intencion_siembra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  http: ^1.2.1
  dio: ^5.9.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.5.3
  bcrypt: ^1.1.3
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  device_preview: 1.3.1

  # Para modelos con Hive
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/logoico.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logoico.png"
  min_sdk_android: 21
